// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type Author struct {
	ID     int       `json:"id"`
	Name   string    `json:"name"`
	Bio    *string   `json:"bio,omitempty"`
	Books  []*Book   `json:"books"`
	Series []*Series `json:"series"`
}

type Book struct {
	ID            int           `json:"id"`
	Title         string        `json:"title"`
	Isbn          *string       `json:"isbn,omitempty"`
	Isbn13        *string       `json:"isbn13,omitempty"`
	PublishedDate *time.Time    `json:"publishedDate,omitempty"`
	PageCount     *int          `json:"pageCount,omitempty"`
	Description   *string       `json:"description,omitempty"`
	CoverURL      *string       `json:"coverURL,omitempty"`
	Owned         bool          `json:"owned"`
	Read          bool          `json:"read"`
	AuthorID      int           `json:"authorID"`
	Author        *Author       `json:"author"`
	Series        []*SeriesBook `json:"series"`
	Tags          []*Tag        `json:"tags"`
}

type CreateAuthorInput struct {
	Name string  `json:"name"`
	Bio  *string `json:"bio,omitempty"`
}

type CreateBookInput struct {
	Title         string     `json:"title"`
	AuthorID      int        `json:"authorID"`
	Isbn          *string    `json:"isbn,omitempty"`
	Isbn13        *string    `json:"isbn13,omitempty"`
	PublishedDate *time.Time `json:"publishedDate,omitempty"`
	PageCount     *int       `json:"pageCount,omitempty"`
	Description   *string    `json:"description,omitempty"`
	Owned         *bool      `json:"owned,omitempty"`
}

type CreateSeriesInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type ExternalBook struct {
	Title            *string   `json:"title,omitempty"`
	AuthorName       []*string `json:"authorName,omitempty"`
	Isbn             []*string `json:"isbn,omitempty"`
	FirstPublishYear *int      `json:"firstPublishYear,omitempty"`
	CoverID          *string   `json:"coverID,omitempty"`
	Key              *string   `json:"key,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type ScanResult struct {
	Book          *Book         `json:"book,omitempty"`
	External      *ExternalBook `json:"external,omitempty"`
	AlreadyExists *bool         `json:"alreadyExists,omitempty"`
}

type Series struct {
	ID           int           `json:"id"`
	Name         string        `json:"name"`
	Description  *string       `json:"description,omitempty"`
	Books        []*SeriesBook `json:"books"`
	MissingBooks []*Book       `json:"missingBooks"`
}

type SeriesBook struct {
	BookID   int     `json:"bookID"`
	SeriesID int     `json:"seriesID"`
	Book     *Book   `json:"book"`
	Series   *Series `json:"series"`
	Position int     `json:"position"`
}

type Tag struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateAuthorInput struct {
	Name *string `json:"name,omitempty"`
	Bio  *string `json:"bio,omitempty"`
}

type UpdateBookInput struct {
	Title         *string    `json:"title,omitempty"`
	Isbn          *string    `json:"isbn,omitempty"`
	Isbn13        *string    `json:"isbn13,omitempty"`
	PublishedDate *time.Time `json:"publishedDate,omitempty"`
	PageCount     *int       `json:"pageCount,omitempty"`
	Description   *string    `json:"description,omitempty"`
}

type UpdateSeriesInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}
