package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/user/library-api/internal/db"
	"github.com/user/library-api/internal/openlibrary"
)

func dbToGraphQLAuthor(a db.Author) *Author {
	author := &Author{
		ID:   int(a.ID),
		Name: a.Name,
	}
	if a.Bio.Valid {
		author.Bio = &a.Bio.String
	}
	return author
}

func dbToGraphQLBook(b db.Book) *Book {
	book := &Book{
		ID:    int(b.ID),
		Title: b.Title,
		Owned: b.Owned,
	}
	if b.Isbn.Valid {
		s := b.Isbn.String
		book.Isbn = &s
	}
	if b.Isbn13.Valid {
		s := b.Isbn13.String
		book.Isbn13 = &s
	}
	if b.PublishedDate.Valid {
		t := b.PublishedDate.Time
		book.PublishedDate = &t
	}
	if b.PageCount.Valid {
		n := int(b.PageCount.Int32)
		book.PageCount = &n
	}
	if b.Description.Valid {
		s := b.Description.String
		book.Description = &s
	}
	if b.CoverUrl.Valid {
		s := b.CoverUrl.String
		book.CoverURL = &s
	}
	return book
}

func olToExternalBook(data *openlibrary.BookData) *ExternalBook {
	result := &ExternalBook{}
	if data.Title != "" {
		result.Title = &data.Title
	}
	for _, a := range data.Authors {
		name := a.Name
		result.AuthorName = append(result.AuthorName, &name)
	}
	for _, isbn := range data.Identifiers.ISBN13 {
		s := isbn
		result.Isbn = append(result.Isbn, &s)
	}
	if len(result.Isbn) == 0 {
		for _, isbn := range data.Identifiers.ISBN10 {
			s := isbn
			result.Isbn = append(result.Isbn, &s)
		}
	}
	if data.URL != "" {
		result.Key = &data.URL
	}
	if data.Cover.Medium != "" {
		result.CoverID = &data.Cover.Medium
	}
	return result
}

// ScanAndAddBook is the resolver for the scanAndAddBook field.
func (r *mutationResolver) ScanAndAddBook(ctx context.Context, isbn string) (*ScanResult, error) {
	existing, err := r.Store.GetBookByISBN(ctx, pgtype.Text{String: isbn, Valid: true})
	if err == nil {
		exists := true
		return &ScanResult{
			Book:          dbToGraphQLBook(existing),
			AlreadyExists: &exists,
		}, nil
	}

	olData, err := r.OLClient.LookupByISBN(isbn)
	if err != nil {
		return nil, err
	}
	if olData == nil {
		exists := false
		return &ScanResult{
			AlreadyExists: &exists,
		}, nil
	}

	authorName := ""
	if len(olData.Authors) > 0 {
		authorName = olData.Authors[0].Name
	}

	author, err := r.Store.CreateAuthor(ctx, db.CreateAuthorParams{
		Name: authorName,
		Bio:  pgtype.Text{Valid: false},
	})
	if err != nil {
		return nil, err
	}

	var pubDate pgtype.Date
	if olData.PublishDate != "" {
		t, err := time.Parse("January 2, 2006", olData.PublishDate)
		if err != nil {
			t, err = time.Parse("2006", olData.PublishDate)
		}
		if err == nil {
			pubDate = pgtype.Date{Time: t, Valid: true}
		}
	}

	isbn10 := ""
	isbn13 := ""
	for _, v := range olData.Identifiers.ISBN10 {
		isbn10 = v
		break
	}
	for _, v := range olData.Identifiers.ISBN13 {
		isbn13 = v
		break
	}

	var pages pgtype.Int4
	if olData.NumberOfPages > 0 {
		pages = pgtype.Int4{Int32: int32(olData.NumberOfPages), Valid: true}
	}

	book, err := r.Store.CreateBook(ctx, db.CreateBookParams{
		Title:         olData.Title,
		AuthorID:      author.ID,
		Isbn:          pgtype.Text{String: isbn10, Valid: isbn10 != ""},
		Isbn13:        pgtype.Text{String: isbn13, Valid: isbn13 != ""},
		PublishedDate: pubDate,
		PageCount:     pages,
		Description:   pgtype.Text{Valid: false},
		CoverUrl:      pgtype.Text{String: olData.Cover.Medium, Valid: olData.Cover.Medium != ""},
		Owned:         true,
	})
	if err != nil {
		return nil, err
	}

	exists := false
	return &ScanResult{
		Book:          dbToGraphQLBook(book),
		External:      olToExternalBook(olData),
		AlreadyExists: &exists,
	}, nil
}

// LookupByIsbn is the resolver for the lookupByISBN field.
func (r *queryResolver) LookupByIsbn(ctx context.Context, isbn string) (*ExternalBook, error) {
	olData, err := r.OLClient.LookupByISBN(isbn)
	if err != nil {
		return nil, err
	}
	if olData == nil {
		return nil, nil
	}
	return olToExternalBook(olData), nil
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input CreateBookInput) (*Book, error) {
	panic("not implemented")
}

// UpdateBook is the resolver for the updateBook field.
func (r *mutationResolver) UpdateBook(ctx context.Context, id int, input UpdateBookInput) (*Book, error) {
	panic("not implemented")
}

// DeleteBook is the resolver for the deleteBook field.
func (r *mutationResolver) DeleteBook(ctx context.Context, id int) (bool, error) {
	panic("not implemented")
}

// ToggleOwned is the resolver for the toggleOwned field.
func (r *mutationResolver) ToggleOwned(ctx context.Context, id int) (*Book, error) {
	panic("not implemented")
}

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input CreateAuthorInput) (*Author, error) {
	panic("not implemented")
}

// UpdateAuthor is the resolver for the updateAuthor field.
func (r *mutationResolver) UpdateAuthor(ctx context.Context, id int, input UpdateAuthorInput) (*Author, error) {
	panic("not implemented")
}

// DeleteAuthor is the resolver for the deleteAuthor field.
func (r *mutationResolver) DeleteAuthor(ctx context.Context, id int) (bool, error) {
	panic("not implemented")
}

// CreateSeries is the resolver for the createSeries field.
func (r *mutationResolver) CreateSeries(ctx context.Context, input CreateSeriesInput) (*Series, error) {
	panic("not implemented")
}

// UpdateSeries is the resolver for the updateSeries field.
func (r *mutationResolver) UpdateSeries(ctx context.Context, id int, input UpdateSeriesInput) (*Series, error) {
	panic("not implemented")
}

// DeleteSeries is the resolver for the deleteSeries field.
func (r *mutationResolver) DeleteSeries(ctx context.Context, id int) (bool, error) {
	panic("not implemented")
}

// AddBookToSeries is the resolver for the addBookToSeries field.
func (r *mutationResolver) AddBookToSeries(ctx context.Context, bookID int, seriesID int, position int) (*SeriesBook, error) {
	panic("not implemented")
}

// RemoveBookFromSeries is the resolver for the removeBookFromSeries field.
func (r *mutationResolver) RemoveBookFromSeries(ctx context.Context, bookID int, seriesID int) (bool, error) {
	panic("not implemented")
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, name string) (*Tag, error) {
	panic("not implemented")
}

// AddTagToBook is the resolver for the addTagToBook field.
func (r *mutationResolver) AddTagToBook(ctx context.Context, bookID int, tagID int) (*Book, error) {
	panic("not implemented")
}

// RemoveTagFromBook is the resolver for the removeTagFromBook field.
func (r *mutationResolver) RemoveTagFromBook(ctx context.Context, bookID int, tagID int) (*Book, error) {
	panic("not implemented")
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context, owned *bool, authorID *int, tagID *int) ([]*Book, error) {
	panic("not implemented")
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id int) (*Book, error) {
	panic("not implemented")
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*Author, error) {
	panic("not implemented")
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id int) (*Author, error) {
	panic("not implemented")
}

// Series is the resolver for the series field.
func (r *queryResolver) Series(ctx context.Context) ([]*Series, error) {
	panic("not implemented")
}

// SeriesByID is the resolver for the seriesByID field.
func (r *queryResolver) SeriesByID(ctx context.Context, id int) (*Series, error) {
	panic("not implemented")
}

// SeriesMissingBooks is the resolver for the seriesMissingBooks field.
func (r *queryResolver) SeriesMissingBooks(ctx context.Context, seriesID int) ([]*Book, error) {
	panic("not implemented")
}

// SimilarBooks is the resolver for the similarBooks field.
func (r *queryResolver) SimilarBooks(ctx context.Context, bookID int, limit *int) ([]*ExternalBook, error) {
	panic("not implemented")
}

// SimilarSeries is the resolver for the similarSeries field.
func (r *queryResolver) SimilarSeries(ctx context.Context, seriesID int, limit *int) ([]*ExternalBook, error) {
	panic("not implemented")
}

// SearchOpenLibrary is the resolver for the searchOpenLibrary field.
func (r *queryResolver) SearchOpenLibrary(ctx context.Context, query string, limit *int) ([]*ExternalBook, error) {
	panic("not implemented")
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*Tag, error) {
	panic("not implemented")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
