package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/user/library-api/internal/db"
	"github.com/user/library-api/internal/openlibrary"
)

func dbToGraphQLAuthor(a db.Author) *Author {
	author := &Author{
		ID:   int(a.ID),
		Name: a.Name,
	}
	if a.Bio.Valid {
		author.Bio = &a.Bio.String
	}
	return author
}

func dbToGraphQLBook(b db.Book) *Book {
	book := &Book{
		ID:    int(b.ID),
		Title: b.Title,
		Owned: b.Owned,
	}
	if b.Isbn.Valid {
		s := b.Isbn.String
		book.Isbn = &s
	}
	if b.Isbn13.Valid {
		s := b.Isbn13.String
		book.Isbn13 = &s
	}
	if b.PublishedDate.Valid {
		t := b.PublishedDate.Time
		book.PublishedDate = &t
	}
	if b.PageCount.Valid {
		n := int(b.PageCount.Int32)
		book.PageCount = &n
	}
	if b.Description.Valid {
		s := b.Description.String
		book.Description = &s
	}
	if b.CoverUrl.Valid {
		s := b.CoverUrl.String
		book.CoverURL = &s
	}
	return book
}

func olToExternalBook(data *openlibrary.BookData) *ExternalBook {
	result := &ExternalBook{}
	if data.Title != "" {
		result.Title = &data.Title
	}
	for _, a := range data.Authors {
		name := a.Name
		result.AuthorName = append(result.AuthorName, &name)
	}
	for _, isbn := range data.Identifiers.ISBN13 {
		s := isbn
		result.Isbn = append(result.Isbn, &s)
	}
	if len(result.Isbn) == 0 {
		for _, isbn := range data.Identifiers.ISBN10 {
			s := isbn
			result.Isbn = append(result.Isbn, &s)
		}
	}
	if data.URL != "" {
		result.Key = &data.URL
	}
	if data.Cover.Medium != "" {
		result.CoverID = &data.Cover.Medium
	}
	return result
}

// ScanAndAddBook is the resolver for the scanAndAddBook field.
func (r *mutationResolver) ScanAndAddBook(ctx context.Context, isbn string) (*ScanResult, error) {
	existing, err := r.Store.GetBookByISBN(ctx, pgtype.Text{String: isbn, Valid: true})
	if err == nil {
		exists := true
		return &ScanResult{
			Book:          dbToGraphQLBook(existing),
			AlreadyExists: &exists,
		}, nil
	}

	olData, err := r.OLClient.LookupByISBN(isbn)
	if err != nil {
		return nil, err
	}
	if olData == nil {
		exists := false
		return &ScanResult{
			AlreadyExists: &exists,
		}, nil
	}

	authorName := ""
	if len(olData.Authors) > 0 {
		authorName = olData.Authors[0].Name
	}

	author, err := r.Store.CreateAuthor(ctx, db.CreateAuthorParams{
		Name: authorName,
		Bio:  pgtype.Text{Valid: false},
	})
	if err != nil {
		return nil, err
	}

	var pubDate pgtype.Date
	if olData.PublishDate != "" {
		t, err := time.Parse("January 2, 2006", olData.PublishDate)
		if err != nil {
			t, err = time.Parse("2006", olData.PublishDate)
		}
		if err == nil {
			pubDate = pgtype.Date{Time: t, Valid: true}
		}
	}

	isbn10 := ""
	isbn13 := ""
	for _, v := range olData.Identifiers.ISBN10 {
		isbn10 = v
		break
	}
	for _, v := range olData.Identifiers.ISBN13 {
		isbn13 = v
		break
	}

	var pages pgtype.Int4
	if olData.NumberOfPages > 0 {
		pages = pgtype.Int4{Int32: int32(olData.NumberOfPages), Valid: true}
	}

	book, err := r.Store.CreateBook(ctx, db.CreateBookParams{
		Title:         olData.Title,
		AuthorID:      author.ID,
		Isbn:          pgtype.Text{String: isbn10, Valid: isbn10 != ""},
		Isbn13:        pgtype.Text{String: isbn13, Valid: isbn13 != ""},
		PublishedDate: pubDate,
		PageCount:     pages,
		Description:   pgtype.Text{Valid: false},
		CoverUrl:      pgtype.Text{String: olData.Cover.Medium, Valid: olData.Cover.Medium != ""},
		Owned:         true,
	})
	if err != nil {
		return nil, err
	}

	exists := false
	return &ScanResult{
		Book:          dbToGraphQLBook(book),
		External:      olToExternalBook(olData),
		AlreadyExists: &exists,
	}, nil
}

// LookupByIsbn is the resolver for the lookupByISBN field.
func (r *queryResolver) LookupByIsbn(ctx context.Context, isbn string) (*ExternalBook, error) {
	olData, err := r.OLClient.LookupByISBN(isbn)
	if err != nil {
		return nil, err
	}
	if olData == nil {
		return nil, nil
	}
	return olToExternalBook(olData), nil
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input CreateBookInput) (*Book, error) {
	owned := false
	if input.Owned != nil {
		owned = *input.Owned
	}

	book, err := r.Store.CreateBook(ctx, db.CreateBookParams{
		Title:         input.Title,
		AuthorID:      int32(input.AuthorID),
		Isbn:          pgtype.Text{String: ptrToStr(input.Isbn), Valid: input.Isbn != nil},
		Isbn13:        pgtype.Text{String: ptrToStr(input.Isbn13), Valid: input.Isbn13 != nil},
		PublishedDate: timeToPgDate(input.PublishedDate),
		PageCount:     intToPgInt4(input.PageCount),
		Description:   pgtype.Text{String: ptrToStr(input.Description), Valid: input.Description != nil},
		CoverUrl:      pgtype.Text{Valid: false},
		Owned:         owned,
	})
	if err != nil {
		return nil, err
	}

	return dbToGraphQLBook(book), nil
}

// UpdateBook is the resolver for the updateBook field.
func (r *mutationResolver) UpdateBook(ctx context.Context, id int, input UpdateBookInput) (*Book, error) {
	book, err := r.Store.UpdateBook(ctx, db.UpdateBookParams{
		ID:            int32(id),
		Title:         ptrToStr(input.Title),
		Isbn:          pgtype.Text{String: ptrToStr(input.Isbn), Valid: input.Isbn != nil},
		Isbn13:        pgtype.Text{String: ptrToStr(input.Isbn13), Valid: input.Isbn13 != nil},
		PublishedDate: timeToPgDate(input.PublishedDate),
		PageCount:     intToPgInt4(input.PageCount),
		Description:   pgtype.Text{String: ptrToStr(input.Description), Valid: input.Description != nil},
	})
	if err != nil {
		return nil, err
	}

	return dbToGraphQLBook(book), nil
}

// DeleteBook is the resolver for the deleteBook field.
func (r *mutationResolver) DeleteBook(ctx context.Context, id int) (bool, error) {
	err := r.Store.DeleteBook(ctx, int32(id))
	if err != nil {
		return false, err
	}
	return true, nil
}

// ToggleOwned is the resolver for the toggleOwned field.
func (r *mutationResolver) ToggleOwned(ctx context.Context, id int) (*Book, error) {
	book, err := r.Store.ToggleOwned(ctx, int32(id))
	if err != nil {
		return nil, err
	}
	return dbToGraphQLBook(book), nil
}

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input CreateAuthorInput) (*Author, error) {
	author, err := r.Store.CreateAuthor(ctx, db.CreateAuthorParams{
		Name: input.Name,
		Bio:  pgtype.Text{String: ptrToStr(input.Bio), Valid: input.Bio != nil},
	})
	if err != nil {
		return nil, err
	}
	return dbToGraphQLAuthor(author), nil
}

// UpdateAuthor is the resolver for the updateAuthor field.
func (r *mutationResolver) UpdateAuthor(ctx context.Context, id int, input UpdateAuthorInput) (*Author, error) {
	author, err := r.Store.UpdateAuthor(ctx, db.UpdateAuthorParams{
		ID:   int32(id),
		Name: ptrToStr(input.Name),
		Bio:  pgtype.Text{String: ptrToStr(input.Bio), Valid: input.Bio != nil},
	})
	if err != nil {
		return nil, err
	}
	return dbToGraphQLAuthor(author), nil
}

// DeleteAuthor is the resolver for the deleteAuthor field.
func (r *mutationResolver) DeleteAuthor(ctx context.Context, id int) (bool, error) {
	err := r.Store.DeleteAuthor(ctx, int32(id))
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateSeries is the resolver for the createSeries field.
func (r *mutationResolver) CreateSeries(ctx context.Context, input CreateSeriesInput) (*Series, error) {
	series, err := r.Store.CreateSeries(ctx, db.CreateSeriesParams{
		Name:        input.Name,
		Description: pgtype.Text{String: ptrToStr(input.Description), Valid: input.Description != nil},
	})
	if err != nil {
		return nil, err
	}
	return dbToGraphQLSeries(series), nil
}

// UpdateSeries is the resolver for the updateSeries field.
func (r *mutationResolver) UpdateSeries(ctx context.Context, id int, input UpdateSeriesInput) (*Series, error) {
	series, err := r.Store.UpdateSeries(ctx, db.UpdateSeriesParams{
		ID:          int32(id),
		Name:        ptrToStr(input.Name),
		Description: pgtype.Text{String: ptrToStr(input.Description), Valid: input.Description != nil},
	})
	if err != nil {
		return nil, err
	}
	return dbToGraphQLSeries(series), nil
}

// DeleteSeries is the resolver for the deleteSeries field.
func (r *mutationResolver) DeleteSeries(ctx context.Context, id int) (bool, error) {
	err := r.Store.DeleteSeries(ctx, int32(id))
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddBookToSeries is the resolver for the addBookToSeries field.
func (r *mutationResolver) AddBookToSeries(ctx context.Context, bookID int, seriesID int, position int) (*SeriesBook, error) {
	sb, err := r.Store.AddBookToSeries(ctx, db.AddBookToSeriesParams{
		SeriesID: int32(seriesID),
		BookID:   int32(bookID),
		Position: int32(position),
	})
	if err != nil {
		return nil, err
	}

	book, err := r.Store.GetBook(ctx, sb.BookID)
	if err != nil {
		return nil, err
	}

	series, err := r.Store.GetSeries(ctx, sb.SeriesID)
	if err != nil {
		return nil, err
	}

	return &SeriesBook{
		Book:     dbToGraphQLBook(book),
		Series:   dbToGraphQLSeries(series),
		Position: int(sb.Position),
	}, nil
}

// RemoveBookFromSeries is the resolver for the removeBookFromSeries field.
func (r *mutationResolver) RemoveBookFromSeries(ctx context.Context, bookID int, seriesID int) (bool, error) {
	err := r.Store.RemoveBookFromSeries(ctx, db.RemoveBookFromSeriesParams{
		SeriesID: int32(seriesID),
		BookID:   int32(bookID),
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, name string) (*Tag, error) {
	tag, err := r.Store.CreateTag(ctx, name)
	if err != nil {
		return nil, err
	}
	return dbToGraphQLTag(tag), nil
}

// AddTagToBook is the resolver for the addTagToBook field.
func (r *mutationResolver) AddTagToBook(ctx context.Context, bookID int, tagID int) (*Book, error) {
	err := r.Store.AddTagToBook(ctx, db.AddTagToBookParams{
		BookID: int32(bookID),
		TagID:  int32(tagID),
	})
	if err != nil {
		return nil, err
	}

	book, err := r.Store.GetBook(ctx, int32(bookID))
	if err != nil {
		return nil, err
	}
	return dbToGraphQLBook(book), nil
}

// RemoveTagFromBook is the resolver for the removeTagFromBook field.
func (r *mutationResolver) RemoveTagFromBook(ctx context.Context, bookID int, tagID int) (*Book, error) {
	err := r.Store.RemoveTagFromBook(ctx, db.RemoveTagFromBookParams{
		BookID: int32(bookID),
		TagID:  int32(tagID),
	})
	if err != nil {
		return nil, err
	}

	book, err := r.Store.GetBook(ctx, int32(bookID))
	if err != nil {
		return nil, err
	}
	return dbToGraphQLBook(book), nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context, owned *bool, authorID *int, tagID *int) ([]*Book, error) {
	dbBooks, err := r.Store.ListBooks(ctx, db.ListBooksParams{
		Owned:    pgtype.Bool{Bool: ptrToBool(owned), Valid: owned != nil},
		AuthorID: pgtype.Int4{Int32: int32(ptrToInt(authorID)), Valid: authorID != nil},
	})
	if err != nil {
		return nil, err
	}

	books := make([]*Book, len(dbBooks))
	for i, b := range dbBooks {
		books[i] = dbToGraphQLBook(b)
	}
	return books, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id int) (*Book, error) {
	book, err := r.Store.GetBook(ctx, int32(id))
	if err != nil {
		return nil, err
	}
	return dbToGraphQLBook(book), nil
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*Author, error) {
	dbAuthors, err := r.Store.ListAuthors(ctx)
	if err != nil {
		return nil, err
	}

	authors := make([]*Author, len(dbAuthors))
	for i, a := range dbAuthors {
		authors[i] = dbToGraphQLAuthor(a)
	}
	return authors, nil
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id int) (*Author, error) {
	author, err := r.Store.GetAuthor(ctx, int32(id))
	if err != nil {
		return nil, err
	}
	return dbToGraphQLAuthor(author), nil
}

// Series is the resolver for the series field.
func (r *queryResolver) Series(ctx context.Context) ([]*Series, error) {
	dbSeries, err := r.Store.ListSeries(ctx)
	if err != nil {
		return nil, err
	}

	series := make([]*Series, len(dbSeries))
	for i, s := range dbSeries {
		series[i] = dbToGraphQLSeries(s)
	}
	return series, nil
}

// SeriesByID is the resolver for the seriesByID field.
func (r *queryResolver) SeriesByID(ctx context.Context, id int) (*Series, error) {
	series, err := r.Store.GetSeries(ctx, int32(id))
	if err != nil {
		return nil, err
	}
	return dbToGraphQLSeries(series), nil
}

// SeriesMissingBooks is the resolver for the seriesMissingBooks field.
func (r *queryResolver) SeriesMissingBooks(ctx context.Context, seriesID int) ([]*Book, error) {
	dbBooks, err := r.Store.GetMissingBooks(ctx, int32(seriesID))
	if err != nil {
		return nil, err
	}

	books := make([]*Book, len(dbBooks))
	for i, b := range dbBooks {
		books[i] = dbToGraphQLBook(b)
	}
	return books, nil
}

// SimilarBooks is the resolver for the similarBooks field.
func (r *queryResolver) SimilarBooks(ctx context.Context, bookID int, limit *int) ([]*ExternalBook, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	book, err := r.Store.GetBook(ctx, int32(bookID))
	if err != nil {
		return nil, err
	}

	resp, err := r.OLClient.SearchByQuery(book.Title, l)
	if err != nil {
		return nil, err
	}

	results := make([]*ExternalBook, len(resp.Docs))
	for i, doc := range resp.Docs {
		results[i] = docToExternalBook(doc)
	}
	return results, nil
}

// SimilarSeries is the resolver for the similarSeries field.
func (r *queryResolver) SimilarSeries(ctx context.Context, seriesID int, limit *int) ([]*ExternalBook, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	series, err := r.Store.GetSeries(ctx, int32(seriesID))
	if err != nil {
		return nil, err
	}

	resp, err := r.OLClient.SearchByQuery(series.Name, l)
	if err != nil {
		return nil, err
	}

	results := make([]*ExternalBook, len(resp.Docs))
	for i, doc := range resp.Docs {
		results[i] = docToExternalBook(doc)
	}
	return results, nil
}

// SearchOpenLibrary is the resolver for the searchOpenLibrary field.
func (r *queryResolver) SearchOpenLibrary(ctx context.Context, query string, limit *int) ([]*ExternalBook, error) {
	l := 20
	if limit != nil {
		l = *limit
	}

	resp, err := r.OLClient.SearchByQuery(query, l)
	if err != nil {
		return nil, err
	}

	results := make([]*ExternalBook, len(resp.Docs))
	for i, doc := range resp.Docs {
		results[i] = docToExternalBook(doc)
	}
	return results, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*Tag, error) {
	dbTags, err := r.Store.ListTags(ctx)
	if err != nil {
		return nil, err
	}

	tags := make([]*Tag, len(dbTags))
	for i, t := range dbTags {
		tags[i] = dbToGraphQLTag(t)
	}
	return tags, nil
}

func dbToGraphQLSeries(s db.Series) *Series {
	result := &Series{
		ID:   int(s.ID),
		Name: s.Name,
	}
	if s.Description.Valid {
		result.Description = &s.Description.String
	}
	return result
}

func dbToGraphQLTag(t db.Tag) *Tag {
	return &Tag{
		ID:   int(t.ID),
		Name: t.Name,
	}
}

func docToExternalBook(doc openlibrary.Doc) *ExternalBook {
	result := &ExternalBook{
		Title: &doc.Title,
	}
	if len(doc.AuthorName) > 0 {
		names := make([]*string, len(doc.AuthorName))
		for i, n := range doc.AuthorName {
			names[i] = &n
		}
		result.AuthorName = names
	}
	if len(doc.ISBN) > 0 {
		isbns := make([]*string, len(doc.ISBN))
		for i, isbn := range doc.ISBN {
			isbns[i] = &isbn
		}
		result.Isbn = isbns
	}
	if doc.FirstPublishYear > 0 {
		result.FirstPublishYear = &doc.FirstPublishYear
	}
	if doc.CoverID != "" {
		result.CoverID = &doc.CoverID
	}
	if doc.Key != "" {
		result.Key = &doc.Key
	}
	return result
}

func ptrToStr(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func ptrToBool(b *bool) bool {
	if b == nil {
		return false
	}
	return *b
}

func ptrToInt(i *int) int {
	if i == nil {
		return 0
	}
	return *i
}

func timeToPgDate(t *time.Time) pgtype.Date {
	if t == nil {
		return pgtype.Date{Valid: false}
	}
	return pgtype.Date{Time: *t, Valid: true}
}

func intToPgInt4(i *int) pgtype.Int4 {
	if i == nil {
		return pgtype.Int4{Valid: false}
	}
	return pgtype.Int4{Int32: int32(*i), Valid: true}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
