// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author_id, isbn, isbn13, published_date, page_count, description, cover_url, owned)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, author_id, isbn, isbn13, published_date, page_count, description, cover_url, owned, created_at, updated_at
`

type CreateBookParams struct {
	Title         string
	AuthorID      int32
	Isbn          pgtype.Text
	Isbn13        pgtype.Text
	PublishedDate pgtype.Date
	PageCount     pgtype.Int4
	Description   pgtype.Text
	CoverUrl      pgtype.Text
	Owned         bool
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.AuthorID,
		arg.Isbn,
		arg.Isbn13,
		arg.PublishedDate,
		arg.PageCount,
		arg.Description,
		arg.CoverUrl,
		arg.Owned,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Isbn13,
		&i.PublishedDate,
		&i.PageCount,
		&i.Description,
		&i.CoverUrl,
		&i.Owned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author_id, isbn, isbn13, published_date, page_count, description, cover_url, owned, created_at, updated_at
FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Isbn13,
		&i.PublishedDate,
		&i.PageCount,
		&i.Description,
		&i.CoverUrl,
		&i.Owned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByISBN = `-- name: GetBookByISBN :one
SELECT id, title, author_id, isbn, isbn13, published_date, page_count, description, cover_url, owned, created_at, updated_at
FROM books
WHERE isbn = $1 OR isbn13 = $1
`

func (q *Queries) GetBookByISBN(ctx context.Context, isbn pgtype.Text) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByISBN, isbn)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Isbn13,
		&i.PublishedDate,
		&i.PageCount,
		&i.Description,
		&i.CoverUrl,
		&i.Owned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author_id, isbn, isbn13, published_date, page_count, description, cover_url, owned, created_at, updated_at
FROM books
WHERE ($1::boolean IS NULL OR owned = $1)
  AND ($2::int IS NULL OR author_id = $2)
ORDER BY title
`

type ListBooksParams struct {
	Owned    pgtype.Bool
	AuthorID pgtype.Int4
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Owned, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Isbn,
			&i.Isbn13,
			&i.PublishedDate,
			&i.PageCount,
			&i.Description,
			&i.CoverUrl,
			&i.Owned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleOwned = `-- name: ToggleOwned :one
UPDATE books
SET owned = NOT owned,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, author_id, isbn, isbn13, published_date, page_count, description, cover_url, owned, created_at, updated_at
`

func (q *Queries) ToggleOwned(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, toggleOwned, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Isbn13,
		&i.PublishedDate,
		&i.PageCount,
		&i.Description,
		&i.CoverUrl,
		&i.Owned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = COALESCE($2, title),
    isbn = COALESCE($3, isbn),
    isbn13 = COALESCE($4, isbn13),
    published_date = COALESCE($5, published_date),
    page_count = COALESCE($6, page_count),
    description = COALESCE($7, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, author_id, isbn, isbn13, published_date, page_count, description, cover_url, owned, created_at, updated_at
`

type UpdateBookParams struct {
	ID            int32
	Title         string
	Isbn          pgtype.Text
	Isbn13        pgtype.Text
	PublishedDate pgtype.Date
	PageCount     pgtype.Int4
	Description   pgtype.Text
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Isbn,
		arg.Isbn13,
		arg.PublishedDate,
		arg.PageCount,
		arg.Description,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Isbn,
		&i.Isbn13,
		&i.PublishedDate,
		&i.PageCount,
		&i.Description,
		&i.CoverUrl,
		&i.Owned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
