// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        int32
	Name      string
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Book struct {
	ID            int32
	Title         string
	AuthorID      int32
	Isbn          pgtype.Text
	Isbn13        pgtype.Text
	PublishedDate pgtype.Date
	PageCount     pgtype.Int4
	Description   pgtype.Text
	CoverUrl      pgtype.Text
	Owned         bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type BookTag struct {
	BookID int32
	TagID  int32
}

type Series struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SeriesBook struct {
	SeriesID int32
	BookID   int32
	Position int32
}

type Tag struct {
	ID   int32
	Name string
}
