// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBookToSeries = `-- name: AddBookToSeries :one
INSERT INTO series_books (series_id, book_id, position)
VALUES ($1, $2, $3)
RETURNING series_id, book_id, position
`

type AddBookToSeriesParams struct {
	SeriesID int32
	BookID   int32
	Position int32
}

func (q *Queries) AddBookToSeries(ctx context.Context, arg AddBookToSeriesParams) (SeriesBook, error) {
	row := q.db.QueryRow(ctx, addBookToSeries, arg.SeriesID, arg.BookID, arg.Position)
	var i SeriesBook
	err := row.Scan(&i.SeriesID, &i.BookID, &i.Position)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateSeriesParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSeries, arg.Name, arg.Description)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeries = `-- name: DeleteSeries :exec
DELETE FROM series
WHERE id = $1
`

func (q *Queries) DeleteSeries(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSeries, id)
	return err
}

const getMissingBooks = `-- name: GetMissingBooks :many
SELECT b.id, b.title, b.author_id, b.isbn, b.isbn13, b.published_date,
       b.page_count, b.description, b.cover_url, b.owned, b.created_at, b.updated_at
FROM series_books sb
JOIN books b ON b.id = sb.book_id
WHERE sb.series_id = $1 AND b.owned = false
ORDER BY sb.position
`

func (q *Queries) GetMissingBooks(ctx context.Context, seriesID int32) ([]Book, error) {
	rows, err := q.db.Query(ctx, getMissingBooks, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Isbn,
			&i.Isbn13,
			&i.PublishedDate,
			&i.PageCount,
			&i.Description,
			&i.CoverUrl,
			&i.Owned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeries = `-- name: GetSeries :one
SELECT id, name, description, created_at, updated_at
FROM series
WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id int32) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeriesBooks = `-- name: GetSeriesBooks :many
SELECT sb.series_id, sb.book_id, sb.position,
       b.id as book_id, b.title, b.author_id, b.isbn, b.isbn13,
       b.published_date, b.page_count, b.description, b.cover_url, b.owned,
       b.created_at as book_created_at, b.updated_at as book_updated_at
FROM series_books sb
JOIN books b ON b.id = sb.book_id
WHERE sb.series_id = $1
ORDER BY sb.position
`

type GetSeriesBooksRow struct {
	SeriesID      int32
	BookID        int32
	Position      int32
	BookID_2      int32
	Title         string
	AuthorID      int32
	Isbn          pgtype.Text
	Isbn13        pgtype.Text
	PublishedDate pgtype.Date
	PageCount     pgtype.Int4
	Description   pgtype.Text
	CoverUrl      pgtype.Text
	Owned         bool
	BookCreatedAt pgtype.Timestamptz
	BookUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetSeriesBooks(ctx context.Context, seriesID int32) ([]GetSeriesBooksRow, error) {
	rows, err := q.db.Query(ctx, getSeriesBooks, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesBooksRow
	for rows.Next() {
		var i GetSeriesBooksRow
		if err := rows.Scan(
			&i.SeriesID,
			&i.BookID,
			&i.Position,
			&i.BookID_2,
			&i.Title,
			&i.AuthorID,
			&i.Isbn,
			&i.Isbn13,
			&i.PublishedDate,
			&i.PageCount,
			&i.Description,
			&i.CoverUrl,
			&i.Owned,
			&i.BookCreatedAt,
			&i.BookUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesBooksByBookID = `-- name: GetSeriesBooksByBookID :many
SELECT series_id, book_id, position
FROM series_books
WHERE book_id = $1
ORDER BY position
`

func (q *Queries) GetSeriesBooksByBookID(ctx context.Context, bookID int32) ([]SeriesBook, error) {
	rows, err := q.db.Query(ctx, getSeriesBooksByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesBook
	for rows.Next() {
		var i SeriesBook
		if err := rows.Scan(&i.SeriesID, &i.BookID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeries = `-- name: ListSeries :many
SELECT id, name, description, created_at, updated_at
FROM series
ORDER BY name
LIMIT $2
OFFSET $1
`

type ListSeriesParams struct {
	Offset pgtype.Int4
	Limit  pgtype.Int4
}

func (q *Queries) ListSeries(ctx context.Context, arg ListSeriesParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeries, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookFromSeries = `-- name: RemoveBookFromSeries :exec
DELETE FROM series_books
WHERE series_id = $1 AND book_id = $2
`

type RemoveBookFromSeriesParams struct {
	SeriesID int32
	BookID   int32
}

func (q *Queries) RemoveBookFromSeries(ctx context.Context, arg RemoveBookFromSeriesParams) error {
	_, err := q.db.Exec(ctx, removeBookFromSeries, arg.SeriesID, arg.BookID)
	return err
}

const updateSeries = `-- name: UpdateSeries :one
UPDATE series
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateSeriesParams struct {
	ID          int32
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, updateSeries, arg.ID, arg.Name, arg.Description)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
