// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const addTagToBook = `-- name: AddTagToBook :exec
INSERT INTO book_tags (book_id, tag_id)
VALUES ($1, $2)
`

type AddTagToBookParams struct {
	BookID int32
	TagID  int32
}

func (q *Queries) AddTagToBook(ctx context.Context, arg AddTagToBookParams) error {
	_, err := q.db.Exec(ctx, addTagToBook, arg.BookID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getBookTags = `-- name: GetBookTags :many
SELECT t.id, t.name
FROM book_tags bt
JOIN tags t ON t.id = bt.tag_id
WHERE bt.book_id = $1
ORDER BY t.name
`

func (q *Queries) GetBookTags(ctx context.Context, bookID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getBookTags, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name
FROM tags
WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name
FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromBook = `-- name: RemoveTagFromBook :exec
DELETE FROM book_tags
WHERE book_id = $1 AND tag_id = $2
`

type RemoveTagFromBookParams struct {
	BookID int32
	TagID  int32
}

func (q *Queries) RemoveTagFromBook(ctx context.Context, arg RemoveTagFromBookParams) error {
	_, err := q.db.Exec(ctx, removeTagFromBook, arg.BookID, arg.TagID)
	return err
}
